apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: by5zn527t-go 
  janus-idp.io/tekton: by5zn527t-go
  backstage.io/kubernetes-id: by5zn527t-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: by5zn527t-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml